[project]
name = "pairs-trading-regime-stability"
version = "0.1.0"
description = ""
authors = [
    {name = "Ben Jones",email = "benjones1479@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel (>=7.3.0,<8.0.0)",
    "yfinance (>=1.7.0,<2.0.0)",
    "pandas (>=3.0.5,<4.0.0)",
    "numpy (>=2.5.2,<3.0.0)",
    "matplotlib (>=3.11.1,<4.0.0)",
    "statsmodels (>=0.15.0,<0.16.0)"
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
